name: Build Desktop Apps

on:
  workflow_dispatch: # 允许手动触发
  push:
    branches: [ "main", "master" ] # 推送到主分支时触发
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-macos:
    name: Build MacOS
    strategy:
      matrix:
        include:
          - os: macos-14
            arch: arm64
            name: Apple Silicon
          - os: macos-13
            arch: x64
            name: Intel
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build MacOS DMG (${{ matrix.name }})
        # 执行 Compose Desktop 的打包任务
        run: ./gradlew :composeApp:packageReleaseDmg

      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MacOS-App-DMG-${{ matrix.arch }}
          # 上传生成的 DMG 文件
          path: composeApp/build/compose/binaries/**/*.dmg
          if-no-files-found: error

  build-linux:
    name: Build Linux Deb
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fakeroot

      - name: Build Linux Deb
        # 执行 Compose Desktop 的打包任务
        run: ./gradlew :composeApp:packageReleaseDeb

      - name: Upload Deb Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux-App-Deb-x64
          # 上传生成的 Deb 文件
          path: composeApp/build/compose/binaries/**/*.deb
          if-no-files-found: error
